---

- name: Create cinder database
  mysql_db:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ cinder_database_name }}"
  tags: cinder-db

- name: Create cinder database user
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ cinder_database_user }}"
    host: "{{ item }}"
    password: "{{ cinder_database_pass }}"
    priv: "{{ cinder_database_name }}.*:ALL"
  with_items: cinder_database_hosts
  tags: cinder-db

- name: Populate cinder database
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder
  notify: Restart cinder-api services
  tags: cinder-db