---

- name: Copy cinder config file
  template:
    src: "cinder_{{ ansible_distribution }}.conf.j2"
    dest: /etc/cinder/cinder.conf
    owner: root
    group: cinder
    mode: 0640
    backup: yes
  tags: cinder-cfg