---
- hosts: all
  roles:
    - { role: env, tags: env }
    - { role: keystone, tags: keystone, when: 'inventory_hostname in groups["controller"]' }
    - { role: glance, tags: glance, when: 'inventory_hostname in groups["controller"]' }
    - { role: nova, tags: nova }
    - { role: cinder, tags: cinder, when: 'inventory_hostname in groups["controller"]' }
    - { role: neutron, tags: neutron }
    - { role: horizon, tags: horizon, when: 'inventory_hostname in groups["controller"]' }