---

- name: Restart ntp
  service:
    name: "{{ ntp_service }}"
    state: restarted
    enabled: yes

- name: Restart Database Server
  service:
    name: "{{ database_service_name }}"
    state: restarted
    enabled: yes