keystone_packages:
  - openstack-keystone
  - python-keystoneclient

keystone_services:
  - openstack-keystone.service
  
keystone_database_name: keystone
keystone_database_user: keystone
keystone_database_hosts:
  - localhost
  - "{{ groups['os_controller'] }}"
keystone_tenants:
  - { name: 'admin', desc: 'Admin tenant' }
  - { name: 'service', desc: 'Services tenant' }
keystone_admin_name: admin
keystone_admin_email: admin@localhost
keystone_admin_tenant: admin
keystone_admin_role: admin
keystone_service_name: keystone
keystone_service_desc: OpenStack Identity
keystone_service_admin_port: "{{ identity_admin_port }}"
keystone_service_public_port: "{{ identity_public_port }}"
keystone_service_region: regionOne
keystone_service_domain: "{{ identity_domain }}"