nova_database_name: nova
nova_database_user: nova
nova_database_hosts:
  - localhost
  - "{{ groups['controller'] }}"
nova_admin_user: nova
nova_admin_email: nova@localhost
nova_service_name: nova
nova_service_desc: OpenStack Compute Service
nova_role: admin
nova_endpoint_domain: "{{ groups['controller'][0] }}"
nova_endpoint_admin_port: 8774
nova_endpoint_public_port: 8774
nova_endpoint_region: regionOne
nova_metadata_server: "{{ groups['controller'][0] }}"
