#### Time service setting
ntp_package_name: ntp

#### Message service settings
rabbitmq_packages: rabbitmq-server
rabbitmq_services: rabbitmq-server

#### Database Related settings 
database_config:
  - { section: 'mysqld', key: 'bind-address', value: "0.0.0.0"}
  - { section: 'mysqld', key: 'default-storage-engine', value: 'innodb'}
  - { section: 'mysqld', key: 'collation-server', value: 'utf8_general_ci'}
  - { section: 'mysqld', key: 'init-connect', value: "'SET NAMES utf8'"}
  - { section: 'mysqld', key: 'character-set-server', value: 'utf8'}