---

- name: Configure kernel networking params
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items: neutron_network_kernal_params
  tags: neutron-network-sysctl