---

- include_vars: "../vars/{{ ansible_distribution }}.yml"
  when: neutron_api_packages is not defined
  tags: neutron-server-pkgs

- name: Install neutron-server (CentOS) pakages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: neutron_api_packages
  when: ansible_distribution == 'CentOS'
  tags: neutron-server-pkgs

- name: Install neutron-server (Ubuntu) pakages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: no
    cache_valid_time: 7200
  with_items: neutron_api_packages
  when: ansible_distribution == 'Ubuntu'
  tags: neutron-server-pkgs