---

- name: Restart nova-api services
  service: 
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: nova_api_services
  when: inventory_hostname in groups['controller']

- name: Restart nova-compute services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: nova_compute_services
  when: inventory_hostname in groups['compute']