neutron_instance_network_interface: "ansible_{{ neutron_instance_network_interface }}"

## Neutron Options
neutron_database_name: neutron
neutron_database_user: neutron
neutron_database_hosts:
  - localhost
  - "{{ groups['controller'] }}"
neutron_admin_user: neutron
neutron_admin_email: neutron@localhost
neutron_admin_tenant: service
neutron_service_name: neutron
neutron_service_desc: OpenStack Networking Service
neutron_role: admin
neutron_endpoint_domain: "{{ groups['controller'][0] }}"
neutron_endpoint_admin_port: 9696
neutron_endpoint_public_port: 9696
neutron_endpoint_region: regionOne
neutron_controller_configs:

neutron_network_kernal_params:
  - { name: 'net.ipv4.ip_forward', value: 1 }
  - { name: 'net.ipv4.conf.all.rp_filter', value: 0 }
  - { name: 'net.ipv4.conf.default.rp_filter', value: 0 }

neutron_compute_kernal_params:
  - { name: 'net.ipv4.conf.all.rp_filter', value: 0 }
  - { name: 'net.ipv4.conf.default.rp_filter', value: 0 }