cinder_database_name: cinder
cinder_database_user: cinder
cinder_database_hosts:
  - localhost
  - "{{ groups['controller'] }}"
cinder_admin_user: cinder
cinder_admin_email: cinder@localhost
cinder_admin_tenant: service
cinderv1_service_name: cinder
cinderv2_service_name: cinderv2
cinder_service_desc: OpenStack Block Storage Service
cinder_role: admin
cinder_endpoint_domain: "{{ groups['controller'][0] }}"
cinder_endpoint_admin_port: 8776
cinder_endpoint_public_port: 8776
cinder_endpoint_region: regionOne
