---
- name: Install yum-plugin-priorities
  yum:
    name: yum-plugin-priorities
    state: latest

- name: Install EPEL 7
  yum: 
    name: "{{ epel7_package }}"
    state: present

- name: Install Openstack RDO Repository
  yum:
    name: "{{ rdo_repository }}"
    state: present

- name: Upgrade all packages
  yum: 
    name: "*" 
    state: latest