---

- name: Install extra packages (CentOS)
  yum:
    name: "{{ item }}"
    state: latest
  with_items: extra_packages
  when: ansible_distribution == 'CentOS'
  tags: env-extra

- name: Install Openstack Juno Repository (CentOS)
  yum:
    name: "{{ openstack_repo }}"
    state: present
  when: ansible_distribution == 'CentOS'
  tags: env-extra

- name: Upgrade all packages (CentOS)
  yum: 
    name: "*" 
    state: latest
  when: ansible_distribution == 'CentOS'
  tags: env-extra


- name: Install extra packages (Ubuntu)
  apt:
    name: ubuntu-cloud-keyring
    state: latest
    update_cache: yes
    cache_valid_time: 7200
  with_items: extra_packages
  when: ansible_distribution == 'Ubuntu'
  tags: env-extra


- name: Install Openstack Juno Cloud-archive
  apt_repository:
    repo: "{{ openstack_repo }}"
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  tags: env-extra

- name: Upgrade system (Ubuntu)
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 7200
  tags: env-extra
