---

- include_vars: "../vars/{{ ansible_distribution }}.yml"
- include: ntp.yml
- include: hosts.yml
- include: extra_pkgs.yml
- include: selinux.yml
  when: ansible_distribution == 'CentOS'
- include: firewall.yml
- include: database_install.yml
- include: database_config.yml
  when: inventory_hostname in groups['controller']
- include: message.yml
  when: inventory_hostname in groups['controller']