---

- name: Install rabbitmq-server (CentOS)
  yum:
    name: "{{ rabbitmq_packages }}"
    state: latest
  tags: env-message
  when: ansible_distribution == 'CentOS'

- name: Install rabbitmq-server (Ubuntu)
  apt:
    name: "{{ rabbitmq_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 7200
  tags: env-message
  when: ansible_distribution == 'Ubuntu'

- name: Start rabbitmq-server
  service:
    name: "{{ rabbitmq_services }}"
    enabled: yes
    state: started
  tags: env-message

- name: Change guest password
  rabbitmq_user:
    user: guest
    password: "{{ rabbitmq_password }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    force: yes
  tags: env-message