---

- name: Configure local_settings
  template:
    src: "local_settings_{{ ansible_distribution }}.j2"
    dest: "{{ horizon_config_file }}"
    backup: yes
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
    mode: "{{ config_mode }}"
  tags: horizon-cfg
  notify: Restart Openstack Dashboard related services