---

- include: nova-api-install.yml
  when: inventory_hostname in groups['os_controller']
- include: nova-compute-install.yml
  when: inventory_hostname in groups['os_compute']
- include: nova-post.yml
- include: nova-api-tenants.yml
  when: inventory_hostname in groups['os_controller']
- include: nova-api-db-setup.yml
  when: inventory_hostname in groups['os_controller']