---

- name: Modify nova-api config file
  template:
    src: "nova_{{ ansible_distribution }}.conf.j2"
    dest: /etc/nova/nova.conf
    backup: yes
    owner: root
    group: nova
    mode: 0640
  tags: nova-cfg
  when: inventory_hostname in groups['controller'] or inventory_hostname in groups['compute']
  notify:
    - Restart nova-compute services
    - Restart nova-api services