---

- name: Create nova database
  mysql_db:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ nova_database_name }}"
  tags: nova-db

- name: Create nova database user
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ nova_database_user }}"
    password: "{{ nova_database_pass }}"
    host: "{{ item }}"
    priv: "{{ nova_database_name }}.*:ALL"
  with_items: nova_database_hosts
  tags: nova-db

- name: Populate nova database
  shell: su -s /bin/sh -c "nova-manage db sync" nova
  notify: Restart nova-api services
  tags: nova-db